#!/usr/bin/env bash
# Story 19.1 — UAT droplet evidence bundle (Epic 19 Production Launch).
#
# Runs preflight + full UAT smoke and prints a sign-off template.
#
# Usage (on droplet after compose up):
#   PUBLIC_BASE_URL=https://your-droplet.example.com \
#   SMOKE_TENANT_HOST=creativorare.your-droplet.example.com \
#   bash deploy/epic-19-1-evidence.sh
#
# Optional: write evidence markdown alongside stdout:
#   EVIDENCE_OUT=_bmad-output/implementation-artifacts/epic-19-1-evidence.md \
#   bash deploy/epic-19-1-evidence.sh

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if [[ -f .env ]]; then
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi

BASE_URL="${PUBLIC_BASE_URL:-}"
TENANT_HOST="${SMOKE_TENANT_HOST:-}"

echo "== Epic 19.1 evidence bundle =="
echo "Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo ""

if [[ -z "$BASE_URL" ]]; then
  echo "❌ PUBLIC_BASE_URL is required."
  echo "   Example: PUBLIC_BASE_URL=https://203.0.113.10"
  exit 1
fi

if [[ "$BASE_URL" != *localhost* && "$BASE_URL" != *127.0.0.1* && -z "$TENANT_HOST" ]]; then
  echo "❌ SMOKE_TENANT_HOST is required when PUBLIC_BASE_URL is not localhost."
  echo "   Example: SMOKE_TENANT_HOST=creativorare.cohestra.app"
  exit 1
fi

echo "PUBLIC_BASE_URL=${BASE_URL}"
echo "SMOKE_TENANT_HOST=${TENANT_HOST:-<local default>}"
echo ""

echo "== Step 1/3: Preflight (non-strict reCAPTCHA — Story 19.3) =="
bash deploy/preflight-launch.sh
echo ""

echo "== Step 2/3: Docker service status =="
docker compose -f docker-compose.uat.yml ps
echo ""

echo "== Step 3/3: UAT smoke (--full) =="
PUBLIC_BASE_URL="${BASE_URL}" SMOKE_TENANT_HOST="${TENANT_HOST}" bash deploy/uat-smoke.sh --full
echo ""

echo "== Evidence template (paste into sign-off) =="
cat <<EOF
| Field | Value |
|-------|-------|
| Story | 19.1 UAT droplet deploy and stack smoke |
| Date | $(date -u +%Y-%m-%d) |
| PUBLIC_BASE_URL | ${BASE_URL} |
| SMOKE_TENANT_HOST | ${TENANT_HOST:-default.localhost} |
| Preflight | pass |
| uat-smoke.sh --full | pass |
| /ready | $(curl -fsS "${BASE_URL%/}/ready" 2>/dev/null | head -c 120 || echo "check manually") |
| DNS notes | _(wildcard vs nip.io)_ |
| Tenants | _(Pro + Basic bootstrap status)_ |
EOF

if [[ -n "${EVIDENCE_OUT:-}" ]]; then
  mkdir -p "$(dirname "$EVIDENCE_OUT")"
  {
    echo "# Epic 19.1 evidence — $(date -u +%Y-%m-%d)"
    echo ""
    echo "- **PUBLIC_BASE_URL:** ${BASE_URL}"
    echo "- **SMOKE_TENANT_HOST:** ${TENANT_HOST:-default.localhost}"
    echo "- **Preflight:** pass"
    echo "- **uat-smoke.sh --full:** pass"
    echo ""
    echo "Generated by \`deploy/epic-19-1-evidence.sh\`"
  } >"$EVIDENCE_OUT"
  echo ""
  echo "Evidence written to ${EVIDENCE_OUT}"
fi

echo ""
echo "✅ Epic 19.1 evidence bundle complete."
