using Cohestra.Domain.Activities;
using Cohestra.Domain.Clients;

namespace Cohestra.Infrastructure.Seed;

internal static class DemoDataSeedCatalog
{
    internal sealed record Persona(
        string Key,
        string FullName,
        string? Email,
        string? Phone,
        string PhoneCountry,
        LeadStatus LeadStatus,
        bool ConsentGiven,
        bool IsMergeSuspect,
        string? Profession,
        string? Nationality,
        string? Residency,
        string? ReferralSource,
        string? Notes,
        int CreatedDaysAgo,
        IReadOnlyList<string> RegisterOnActivitySlugs,
        IReadOnlyList<TimelineSeed> Timeline);

    internal sealed record TimelineSeed(
        ClientTimelineEventType EventType,
        int DaysAgo,
        string? Subject = null,
        string? Note = null,
        string? PreviousLeadStatus = null,
        string? NewLeadStatus = null);

    internal sealed record ActivitySpec(
        string Slug,
        string Name,
        string CommunityLabel,
        string Category,
        ActivityStatus Status,
        int? MaxRegistrants,
        bool ShowOnHomepage,
        int CreatedDaysAgo,
        IReadOnlyList<string>? RegisterPersonaKeys = null,
        int? SyntheticRegistrationCount = null);

    internal static readonly IReadOnlyList<Persona> Personas =
    [
        new(
            Key: "francis-decena",
            FullName: "Francis Decena",
            Email: "fad16papa@gmail.com",
            Phone: "+6593395840",
            PhoneCountry: "SG",
            LeadStatus: LeadStatus.Active,
            ConsentGiven: true,
            IsMergeSuspect: false,
            Profession: "Software Engineer",
            Nationality: "Filipino",
            Residency: "Singapore",
            ReferralSource: "Friend",
            Notes: "Primary UAT persona — messenger outreach, full profile.",
            CreatedDaysAgo: 14,
            RegisterOnActivitySlugs: ["demo-tgh-tennis-open", "demo-ikigai-pickleball-intro"],
            Timeline:
            [
                new(ClientTimelineEventType.WhatsAppInitiated, 10),
                new(ClientTimelineEventType.WhatsAppFollowUpRecorded, 9, "Contacted", "Welcome message sent"),
                new(ClientTimelineEventType.ViberInitiated, 7),
                new(ClientTimelineEventType.LeadStatusChanged, 8, PreviousLeadStatus: "new", NewLeadStatus: "active"),
            ]),
        new(
            Key: "new-lead-ava",
            FullName: "Ava Tan",
            Email: "ava.tan@example.com",
            Phone: "+6591234567",
            PhoneCountry: "SG",
            LeadStatus: LeadStatus.New,
            ConsentGiven: true,
            IsMergeSuspect: false,
            Profession: "Teacher",
            Nationality: "Singaporean",
            Residency: null,
            ReferralSource: "Instagram",
            Notes: "Needs follow-up — dashboard coverage demo.",
            CreatedDaysAgo: 2,
            RegisterOnActivitySlugs: ["demo-tgh-tennis-open"],
            Timeline: []),
        new(
            Key: "contacted-noah",
            FullName: "Noah Lim",
            Email: "noah.lim@example.com",
            Phone: "+6592234567",
            PhoneCountry: "SG",
            LeadStatus: LeadStatus.Contacted,
            ConsentGiven: true,
            IsMergeSuspect: false,
            Profession: "Marketing Manager",
            Nationality: "Singaporean",
            Residency: null,
            ReferralSource: "WhatsApp group",
            Notes: null,
            CreatedDaysAgo: 9,
            RegisterOnActivitySlugs: ["demo-ikigai-pickleball-intro"],
            Timeline:
            [
                new(ClientTimelineEventType.WhatsAppInitiated, 5),
                new(ClientTimelineEventType.WhatsAppFollowUpRecorded, 4, "Awaiting reply", "Sent schedule options"),
            ]),
        new(
            Key: "campaign-mia",
            FullName: "Mia Chen",
            Email: "mia.chen@example.com",
            Phone: "+6593334567",
            PhoneCountry: "SG",
            LeadStatus: LeadStatus.Active,
            ConsentGiven: true,
            IsMergeSuspect: false,
            Profession: "Product Manager",
            Nationality: "Singaporean",
            Residency: null,
            ReferralSource: "Email newsletter",
            Notes: "Received spring campaign.",
            CreatedDaysAgo: 21,
            RegisterOnActivitySlugs: ["demo-boardgame-night", "demo-tgh-tennis-open"],
            Timeline: []),
        new(
            Key: "inactive-liam",
            FullName: "Liam Wong",
            Email: "liam.wong@example.com",
            Phone: "+6594444567",
            PhoneCountry: "SG",
            LeadStatus: LeadStatus.Inactive,
            ConsentGiven: true,
            IsMergeSuspect: false,
            Profession: "Accountant",
            Nationality: "Malaysian",
            Residency: "Singapore",
            ReferralSource: "Past member",
            Notes: null,
            CreatedDaysAgo: 120,
            RegisterOnActivitySlugs: ["demo-tgh-tennis-open"],
            Timeline:
            [
                new(ClientTimelineEventType.LeadStatusChanged, 30, PreviousLeadStatus: "active", NewLeadStatus: "inactive"),
            ]),
        new(
            Key: "merge-suspect-a",
            FullName: "Sophia Reyes",
            Email: "sophia.reyes@example.com",
            Phone: "+6595555678",
            PhoneCountry: "SG",
            LeadStatus: LeadStatus.New,
            ConsentGiven: true,
            IsMergeSuspect: true,
            Profession: "Nurse",
            Nationality: "Filipino",
            Residency: null,
            ReferralSource: "Friend",
            Notes: "Duplicate phone suspect pair A.",
            CreatedDaysAgo: 5,
            RegisterOnActivitySlugs: ["demo-wellness-morning-yoga"],
            Timeline: []),
        new(
            Key: "merge-suspect-b",
            FullName: "Sophia R.",
            Email: "s.reyes.alt@example.com",
            Phone: "+6595555678",
            PhoneCountry: "SG",
            LeadStatus: LeadStatus.New,
            ConsentGiven: true,
            IsMergeSuspect: true,
            Profession: null,
            Nationality: "Filipino",
            Residency: null,
            ReferralSource: "Friend",
            Notes: "Duplicate phone suspect pair B.",
            CreatedDaysAgo: 4,
            RegisterOnActivitySlugs: [],
            Timeline: []),
        new(
            Key: "email-only-emma",
            FullName: "Emma Davis",
            Email: "emma.davis@example.com",
            Phone: null,
            PhoneCountry: "SG",
            LeadStatus: LeadStatus.New,
            ConsentGiven: true,
            IsMergeSuspect: false,
            Profession: "Designer",
            Nationality: "British",
            Residency: null,
            ReferralSource: "Website",
            Notes: "No phone — messenger buttons disabled.",
            CreatedDaysAgo: 3,
            RegisterOnActivitySlugs: ["demo-boardgame-night"],
            Timeline: []),
        new(
            Key: "no-consent-james",
            FullName: "James Patel",
            Email: "james.patel@example.com",
            Phone: "+6596664567",
            PhoneCountry: "SG",
            LeadStatus: LeadStatus.Contacted,
            ConsentGiven: false,
            IsMergeSuspect: false,
            Profession: "Chef",
            Nationality: "Indian",
            Residency: null,
            ReferralSource: "Walk-in",
            Notes: "Consent false — campaign segment exclusion.",
            CreatedDaysAgo: 11,
            RegisterOnActivitySlugs: ["demo-tgh-tennis-open"],
            Timeline: []),
        new(
            Key: "ph-mobile-maria",
            FullName: "Maria Santos",
            Email: "maria.santos@example.com",
            Phone: "+639171234567",
            PhoneCountry: "PH",
            LeadStatus: LeadStatus.Active,
            ConsentGiven: true,
            IsMergeSuspect: false,
            Profession: "Physiotherapist",
            Nationality: "Filipino",
            Residency: "Philippines",
            ReferralSource: "Viber community",
            Notes: "PH E.164 — Viber deep link normalization.",
            CreatedDaysAgo: 16,
            RegisterOnActivitySlugs: ["demo-ikigai-pickleball-intro"],
            Timeline:
            [
                new(ClientTimelineEventType.ViberInitiated, 3),
            ]),
        new(
            Key: "viber-awaiting-ken",
            FullName: "Ken Suzuki",
            Email: "ken.suzuki@example.com",
            Phone: "+6597774567",
            PhoneCountry: "SG",
            LeadStatus: LeadStatus.Contacted,
            ConsentGiven: true,
            IsMergeSuspect: false,
            Profession: "Architect",
            Nationality: "Japanese",
            Residency: "Singapore",
            ReferralSource: "Event QR",
            Notes: null,
            CreatedDaysAgo: 7,
            RegisterOnActivitySlugs: ["demo-marina-social-meetup"],
            Timeline:
            [
                new(ClientTimelineEventType.ViberInitiated, 2),
                new(ClientTimelineEventType.WhatsAppInitiated, 6),
            ]),
    ];

    internal static readonly IReadOnlyList<ActivitySpec> ScenarioActivities =
    [
        new(
            Slug: "demo-tgh-tennis-open",
            Name: "TGH Tennis Club — Open Session",
            CommunityLabel: "TGH Tennis Club",
            Category: "Sports",
            Status: ActivityStatus.Published,
            MaxRegistrants: null,
            ShowOnHomepage: true,
            CreatedDaysAgo: 30,
            RegisterPersonaKeys: null,
            SyntheticRegistrationCount: 18),
        new(
            Slug: "demo-ikigai-pickleball-intro",
            Name: "Ikigai Pickleball — Intro Class",
            CommunityLabel: "Ikigai Pickleball",
            Category: "Sports",
            Status: ActivityStatus.Published,
            MaxRegistrants: 5,
            ShowOnHomepage: true,
            CreatedDaysAgo: 25,
            RegisterPersonaKeys: ["francis-decena", "new-lead-ava", "contacted-noah", "ph-mobile-maria", "no-consent-james"],
            SyntheticRegistrationCount: 0),
        new(
            Slug: "demo-boardgame-night",
            Name: "Ikigai Board Game Night",
            CommunityLabel: "Ikigai Board Games",
            Category: "Social",
            Status: ActivityStatus.Published,
            MaxRegistrants: 20,
            ShowOnHomepage: true,
            CreatedDaysAgo: 20,
            RegisterPersonaKeys: null,
            SyntheticRegistrationCount: 8),
        new(
            Slug: "demo-wellness-morning-yoga",
            Name: "Harbor Wellness — Morning Yoga",
            CommunityLabel: "Harbor Wellness Circle",
            Category: "Wellness",
            Status: ActivityStatus.Published,
            MaxRegistrants: 15,
            ShowOnHomepage: false,
            CreatedDaysAgo: 18,
            RegisterPersonaKeys: null,
            SyntheticRegistrationCount: 6),
        new(
            Slug: "demo-marina-social-meetup",
            Name: "Marina Pickleball — Member Social",
            CommunityLabel: "Marina Pickleball Club",
            Category: "Social",
            Status: ActivityStatus.Published,
            MaxRegistrants: null,
            ShowOnHomepage: true,
            CreatedDaysAgo: 12,
            RegisterPersonaKeys: ["viber-awaiting-ken"],
            SyntheticRegistrationCount: 10),
        new(
            Slug: "demo-runners-draft-clinic",
            Name: "Riverside Runners — Skills Clinic (Draft)",
            CommunityLabel: "Riverside Runners",
            Category: "Sports",
            Status: ActivityStatus.Draft,
            MaxRegistrants: null,
            ShowOnHomepage: false,
            CreatedDaysAgo: 5,
            RegisterPersonaKeys: null,
            SyntheticRegistrationCount: 0),
        new(
            Slug: "demo-sunset-archived-social",
            Name: "Sunset Board Gamers — Archived Social",
            CommunityLabel: "Sunset Board Gamers",
            Category: "Social",
            Status: ActivityStatus.Archived,
            MaxRegistrants: null,
            ShowOnHomepage: false,
            CreatedDaysAgo: 90,
            RegisterPersonaKeys: ["inactive-liam"],
            SyntheticRegistrationCount: 0),
    ];

    internal const string DemoCampaignSubject = "Spring community update";

    internal const string DemoCampaignBody =
        "Hi {{first_name}},\n\nOur spring schedule is live. Register for upcoming sessions on our homepage.\n\n— The team";
}
